// @json-render/svelte@0.20.0 exports .svelte source, so Node cannot import it
// to enumerate exports. Keep this list aligned with the pinned package.
export const jsonRenderSvelteExports = [
	'StateProvider',
	'getStateContext',
	'getStateValue',
	'getBoundProp',
	'VisibilityProvider',
	'getVisibilityContext',
	'isVisible',
	'ActionProvider',
	'getActionContext',
	'getAction',
	'ValidationProvider',
	'getValidationContext',
	'getOptionalValidationContext',
	'getFieldValidation',
	'RepeatScopeProvider',
	'getRepeatScope',
	'FunctionsContextProvider',
	'getFunctions',
	'DirectivesContextProvider',
	'getDirectives',
	'schema',
	'flatToTree',
	'buildSpecFromParts',
	'getTextFromParts',
	'createUIStream',
	'createChatUI',
	'defineRegistry',
	'createRenderer',
	'Renderer',
	'CatalogRenderer',
	'JsonUIProvider',
	'ConfirmDialog',
	'ConfirmDialogManager',
];
