[package]
name = "unity-agent"
version = "0.1.0"
description = "Gizmo, an AI workbench for Unity"
authors = ["genge"]
edition = "2021"

[lib]
name = "unity_agent_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
