import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Regenerates the embedded source for first-party Pi extensions. The agent
 * server embeds these as strings (the compiled sidecar has no repo files on
 * disk) and seeds them into the data dir, where Pi loads them like any other
 * extension.
 *
 * Run after editing a Pi extension: `pnpm extensions:generate`.
 */

const extensions: readonly { file: string; source: string }[] = [
	{ file: 'ask-user.ts', source: 'packages/ask-user/pi-extension.ts' },
];

async function main() {
	const out = join(
		import.meta.dirname,
		'..',
		'apps/agent-server/src/pi-extensions',
	);

	for (const extension of extensions) {
		const source = await readFile(
			join(import.meta.dirname, '..', extension.source),
			'utf8',
		);
		const identifier =
			extension.file
				.replace(/\.ts$/, '')
				.split('-')
				.map((part) => part[0]!.toUpperCase() + part.slice(1))
				.join('') + 'Source';
		const target = join(out, extension.file.replace(/\.ts$/, '-source.ts'));
		const module = `/**
 * Generated by scripts/generate-pi-extension-source.ts — edit
 * ${extension.source} and regenerate instead of editing this file.
 */
export const ${identifier} = ${JSON.stringify(source)};
`;
		await writeFile(target, module);
		console.log(`generated ${target}`);
	}
}

main();
