import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/**
 * Regenerates the embedded source for first-party Pi extensions. The agent
 * server embeds these as strings (the compiled sidecar has no repo files on
 * disk) and seeds them into the data dir, where Pi loads them like any other
 * extension.
 *
 * Run after editing a file in pi-extensions/: `pnpm extensions:generate`.
 */

async function main() {
	const extensions = ['ask-user.ts'];
	const out = join(
		import.meta.dirname,
		'..',
		'apps/agent-server/src/pi-extensions',
	);

	for (const name of extensions) {
		const source = await readFile(
			join(import.meta.dirname, '..', 'pi-extensions', name),
			'utf8',
		);
		const target = join(out, name.replace(/\.ts$/, '-source.ts'));
		const module = `/**
 * Generated by scripts/generate-pi-extension-source.ts — edit
 * pi-extensions/${name} and regenerate instead of editing this file.
 */
export const ${name
			.replace(/\.ts$/, '')
			.split('-')
			.map((part) => part[0]!.toUpperCase() + part.slice(1))
			.join('')}Source = ${JSON.stringify(source)};
`;
		await writeFile(target, module);
		console.log(`generated ${target}`);
	}
}

main();
