import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Regenerates the embedded source for first-party Pi extensions. The agent
 * server embeds these as strings (the compiled sidecar has no repo files on
 * disk) and seeds them into the data dir, where Pi loads them like any other
 * extension.
 *
 * Run after editing a Pi extension: `pnpm extensions:generate`.
 * Web bundles build separately: `pnpm pi-extensions:build`.
 */

const extensions: readonly { file: string; source: string }[] = [
	{ file: 'ask-user.ts', source: 'pi-extensions/ask-user/pi-extension.ts' },
];

async function main() {
	const out = join(
		import.meta.dirname,
		'..',
		'apps/agent-server/src/pi-extensions',
	);

	for (const extension of extensions) {
		const stem = extension.file.replace(/\.ts$/, '');
		const identifier =
			stem
				.split('-')
				.map((part) => part[0]!.toUpperCase() + part.slice(1))
				.join('') + 'Source';
		const source = await readFile(
			join(import.meta.dirname, '..', extension.source),
			'utf8',
		);
		const target = join(out, `${stem}-source.ts`);
		const module = `/**
 * Generated by scripts/generate-pi-extension-source.ts — edit
 * ${extension.source} and regenerate instead of editing this file.
 */
export const ${identifier} = ${JSON.stringify(source)};
`;
		await writeFile(target, module);
		console.log(`generated ${target}`);

		const webBundle = join(
			import.meta.dirname,
			'..',
			'pi-extensions',
			`${stem}.web.js`,
		);
		try {
			const webSource = await readFile(webBundle, 'utf8');
			const webTarget = join(out, `${stem}-web-source.ts`);
			const webModule = `/**
 * Generated by scripts/generate-pi-extension-source.ts from the built
 * pi-extensions/${stem}.web.js bundle (pnpm pi-extensions:build).
 */
export const ${identifier.replace(/Source$/, 'WebSource')} = ${JSON.stringify(webSource)};
`;
			await writeFile(webTarget, webModule);
			console.log(`generated ${webTarget}`);
		} catch {
			// The extension ships no web UI, or it has not been built yet.
		}
	}
}

main();
