import type { ProviderStatus } from '@gizmo/protocol';

/**
 * A cross-section of the real catalog rather than one entry: the providers
 * list is long and mixed, and every credential state — OAuth, a stored key,
 * an environment key, nothing at all — has to be visible while working on it.
 */
export const fakeProviders: ProviderStatus[] = [
	{
		id: 'openai-codex',
		name: 'OpenAI Codex',
		authenticated: true,
		source: 'OAuth',
		credentialType: 'oauth',
		supportsApiKey: false,
		supportsOAuth: true,
		modelCount: 3,
	},
	{
		id: 'opencode-go',
		name: 'OpenCode Go',
		authenticated: true,
		source: 'stored credential',
		credentialType: 'api_key',
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 27,
	},
	{
		id: 'anthropic',
		name: 'Anthropic',
		authenticated: true,
		source: 'ANTHROPIC_API_KEY',
		credentialType: 'api_key',
		supportsApiKey: true,
		supportsOAuth: true,
		modelCount: 13,
	},
	{
		id: 'amazon-bedrock',
		name: 'Amazon Bedrock',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 118,
	},
	{
		id: 'ant-ling',
		name: 'Ant Ling',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 3,
	},
	{
		id: 'azure-openai',
		name: 'Azure OpenAI',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 38,
	},
	{
		id: 'google-vertex',
		name: 'Google Vertex',
		authenticated: false,
		supportsApiKey: false,
		supportsOAuth: true,
		modelCount: 21,
	},
	{
		id: 'groq',
		name: 'Groq',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 9,
	},
	{
		id: 'mistral',
		name: 'Mistral',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 16,
	},
	{
		id: 'ollama',
		name: 'Ollama',
		authenticated: false,
		supportsApiKey: false,
		supportsOAuth: false,
		modelCount: 0,
	},
	{
		id: 'openrouter',
		name: 'OpenRouter',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 312,
	},
	{
		id: 'xai',
		name: 'xAI',
		authenticated: false,
		supportsApiKey: true,
		supportsOAuth: false,
		modelCount: 7,
	},
];
